ALTER TABLE TRANSAKSI ADD FOREIGN KEY (NIK) REFERENCES CUSTOMER(NIK);
ALTER TABLE TRANSAKSI ADD FOREIGN KEY (ID_PETUGAS) REFERENCES PETUGAS(ID_PETUGAS);
ALTER TABLE TRANSAKSI ADD FOREIGN KEY (ID_PAKETHARGA) REFERENCES PAKET_HARGA(ID_PAKETHARGA);
