CREATE TABLE TRANSAKSI(
  NO_NOTA VARCHAR(6) NOT NULL PRIMARY KEY,
  NIK VARCHAR(16) NOT NULL ,
  ID_PETUGAS VARCHAR(5) NOT NULL ,
  ID_PAKETHARGA VARCHAR(3) NOT NULL ,
  NAMA_CUSTOMER VARCHAR(35) NOT NULL ,
  TANGGAL_MASUK DATE NOT NULL ,
  TANGGAL_KELUAR DATE NOT NULL ,
  TOTAL INT(7) NOT NULL
)
